### ISSUE TITLE
Migrate to Django 5

### ISSUE THREAD

**Issue by imbev** [SANTHOSH-MAMIDISETTI/robotics_club_management#2]
Django 5 is the latest major version of Django. I suggest migration to Django 5 to avoid future EOL and for the latest features.

**Comment by SANTHOSH-MAMIDISETTI** [comment]
> Django 5 is the latest major version of Django. I suggest migration to Django 5 to avoid future EOL and for the latest features.

Thank you for the suggestion, @imbev! Migrating to Django 5 could indeed be valuable to stay up-to-date with the latest features and ensure long-term support.

Since the project is still relatively early in development, with much yet to be implemented, moving to Django 5 now makes sense to avoid compatibility issues down the road. We’ll need to review compatibility with existing code and dependencies(if any). If you’re interested in exploring this further, feel free to start with an initial compatibility check, and we can work together on any adjustments. Thanks again for opening this issue!

**Comment by SANTHOSH-MAMIDISETTI** [comment]
The project is using Django 5.1.2 now. Thanks for checking @imbev  ! Closing this issue now.
